
name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure dpkg to skip docs
      run: |
        sudo mkdir -p /etc/dpkg/dpkg.cfg.d
        echo "path-exclude /usr/share/doc/*" | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc
        echo "path-exclude /usr/share/man/*" | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          automake \
          autoconf \
          pkg-config \
          libxml2-dev \
          libefl-all-dev \
          libeet-bin \
          libeina-bin

    - name: Generate build system
      run: autoreconf --install

    - name: Configure project
      run: ./configure

    - name: Build application
      run: make

    - name: Run tests
      run: |
        cd src
        make test_basic
        ./test_basic
