name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Update package lists
      run: sudo apt-get update
      
    - name: Install build essentials
      run: sudo apt-get install -y build-essential automake autoconf

    - name: Install EFL development packages
      run: |
        sudo apt-get install -y \
          libefl-all-dev \
          libeet-bin \
          libeina-bin

    - name: Install pkg-config
      run: sudo apt-get install -y pkg-config

    - name: Generate build system
      run: autoreconf --install

    - name: Configure project
      run: ./configure

    - name: Build application
      run: make
