
name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          automake \
          autoconf \
          pkg-config \
          libxml2-dev \
          libefl-all-dev \
          libeet-bin \
          libeina-bin

    - name: Generate build system
      run: autoreconf --install

    - name: Configure project
      run: ./configure

    - name: Build application
      run: make
